name: Build, Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configure Maven settings for GitHub Packages
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.TOKEN }}</password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml

    - name: Build and test the project
      run: mvn -f pandas-java/pom.xml clean verify

    - name: Generate JaCoCo coverage report
      run: mvn -f pandas-java/pom.xml jacoco:report

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: pandas-java/target/site/jacoco/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        
    - name: Deploy to GitHub Packages
      run: mvn -f pandas-java/pom.xml deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: annaclavelier/pandas-java-demo:latest

    